version: 1.0.{build}
os: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- ps: git config --global core.autocrlf true
before_build:
- nuget restore
skip_tags: true
build:
  verbosity: minimal
artifacts:
- path: 'Tvl.VisualStudio.InheritanceMargin\bin\Release\net45\Tvl.VisualStudio.InheritanceMargin.vsix'
# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
